# AUTO-GENERATED by scripts/generate_legal_drafts.py — do not edit by hand.
# Regenerate with: python scripts/generate_legal_drafts.py
# Last generated: 2026-07-17T11:17:08.857679Z

DRAFT_LEGAL_DOCS = [
    {"slug": "01-terms-of-service", "display_name": "Terms of Service (Draft)", "category": "Public-facing"},
    {"slug": "02-privacy-policy", "display_name": "Privacy Policy (Draft)", "category": "Public-facing"},
    {"slug": "03-cookie-notice", "display_name": "Cookie & Tracking Notice (Draft)", "category": "Public-facing"},
    {"slug": "04-indemnification-hold-harmless", "display_name": "Universal Indemnification & Hold-Harmless Agreement (Draft)", "category": "Public-facing"},
    {"slug": "05-facilitator-services-agreement", "display_name": "Facilitator Services Agreement + IP Assignment (Draft)", "category": "Partner agreements"},
    {"slug": "06-artist-consignment-agreement", "display_name": "Artist Consignment / Gallery Partner Agreement (Draft)", "category": "Partner agreements"},
    {"slug": "07-vendor-supplier-agreement", "display_name": "Vendor Supplier / Dropship Agreement (Draft, 7C's Farmstead first)", "category": "Partner agreements"},
    {"slug": "08-community-partner-referral-agreement", "display_name": "Community Partner Referral Agreement (Draft)", "category": "Partner agreements"},
    {"slug": "09-sponsorship-agreement", "display_name": "Sponsorship Agreement / Sponsor Recognition Consent (Draft)", "category": "Partner agreements"},
    {"slug": "10-sliding-scale-scholarship-terms", "display_name": "Sliding-Scale & Scholarship Terms (Draft)", "category": "Public-facing"},
    {"slug": "11-board-officer-agreement", "display_name": "Board Member / Officer Agreement + D&O Coverage (Draft)", "category": "Governance"},
    {"slug": "12-volunteer-agreement", "display_name": "Foundation Working-Group Volunteer Agreement (Draft)", "category": "Governance"},
    {"slug": "13-ombudsman-charter", "display_name": "Ombudsman Charter (Draft)", "category": "Governance"},
    {"slug": "14-community-standards", "display_name": "Content Moderation & Community Standards Policy (Draft)", "category": "Public-facing"},
    {"slug": "15-refund-returns-policy", "display_name": "Refund & Returns Policy (Draft, Public)", "category": "Public-facing"},
    {"slug": "16-sales-tax-registration-plan", "display_name": "Sales-Tax Registration Plan (Draft)", "category": "Internal / Compliance"},
    {"slug": "17-trademark-filings-plan", "display_name": "Trademark Filings Plan (Draft)", "category": "Internal / IP"},
    {"slug": "18-copyright-registration-strategy", "display_name": "Copyright Registration Strategy (Draft)", "category": "Internal / IP"},
    {"slug": "19-data-processing-agreement-template", "display_name": "Data Processing Agreement Template (Draft)", "category": "Governance"},
    {"slug": "20-nonprofit-governance-bundle", "display_name": "Nonprofit Governance Bundle (Draft — Articles, Bylaws, COI, Whistleblower, Retention)", "category": "Governance"},
    {"slug": "21-charitable-solicitation-plan", "display_name": "State Charitable Solicitation Registration Plan (Draft)", "category": "Internal / Compliance"},
    {"slug": "22-istv-contract-analysis-memo", "display_name": "ISTV Contract — Full Text Review & Business Value Memo", "category": "Advisory memos"},
]
