"""Generate first-draft legal instruments for counsel review.

Each output file lives under /app/backend/legal_docs/ and is registered in
routers/legal.py::LEGAL_DOC_INDEX so it shows up on /admin/legal-docs.

⚠️  Every draft carries a prominent "AI-generated first draft, not legal
    advice" disclaimer at the top and bottom. Counsel must review, revise,
    and ratify each before publishing.

Run:  python /app/backend/scripts/generate_legal_drafts.py
"""
from pathlib import Path
from datetime import datetime

OUT = Path(__file__).resolve().parent.parent / "legal_docs"
OUT.mkdir(parents=True, exist_ok=True)

DISCLAIMER_TOP = """> ⚠️ **AI-GENERATED FIRST DRAFT — NOT LEGAL ADVICE**
>
> This document was generated by an AI assistant as a starting point for
> outside counsel. It is not legal advice, has not been reviewed by an
> attorney, and MUST NOT be published, executed, or relied upon in its
> current form. Counsel must review, revise, adapt to the entity form and
> state of incorporation, and ratify before any use.
>
> Version: February 2026 · Generated for: Birthright Foundation
> (birthright.live) · Executive Director: Amanda Reagan
"""

DISCLAIMER_BOTTOM = """
---
_This document is an AI-generated first draft prepared for outside counsel
review. It is not legal advice, has not been reviewed by an attorney, and
must not be published or executed without counsel review and ratification._
"""

# ---------------------------------------------------------------------------
# Every entry: (slug, display_name, category, body_markdown)
# ---------------------------------------------------------------------------
DOCS = [

# ---------- 1. TERMS OF SERVICE ----------
("01-terms-of-service", "Terms of Service (Draft)", "Public-facing", """
# Terms of Service — Birthright Foundation (Draft)

## 1. Acceptance
By creating an account at birthright.live, purchasing a product, registering
for a workshop, or otherwise using our platform (the "Services"), you agree
to these Terms of Service. If you do not agree, do not use the Services.

## 2. Who We Are
Birthright Foundation ("Birthright," "we," "us") operates the platform at
birthright.live and its subdomains. Contact: hello@birthright.live.

## 3. Eligibility
You must be at least eighteen (18) years old to create an account, make a
purchase, register for a workshop, post community content, or become a
Partner. By using the Services you represent that you meet this requirement.

## 4. Account
You are responsible for maintaining the confidentiality of your credentials
and for all activity under your account. You agree to provide accurate
information at registration and to keep it current.

## 5. Purchases, Workshops & Digital Content
- **Products**: Physical goods listed under /equip. Fulfilled by Birthright,
  print-on-demand partners (Printful, Lulu), or vendor partners (e.g.,
  7C's Farmstead). See our Refund & Returns Policy.
- **Workshops**: Live and recorded educational sessions. Sliding-scale
  pricing may apply — see the Sliding-Scale & Scholarship Terms.
- **Subscriptions & Sponsorships**: Recurring charges continue until you
  cancel through your dashboard. Cancellation is prospective; already-paid
  periods are not refunded except where required by law.
- **AI Wallet**: Prepaid credits consumed by AI 1:1 features. Unused credits
  are non-transferable and non-refundable.
- **Donations**: One-time contributions. Tax deductibility depends on our
  federal tax status at the time of your gift; consult your tax advisor.

## 6. User Conduct
You agree not to (a) impersonate any person, (b) upload unlawful, harassing,
threatening, or infringing content, (c) reverse-engineer or scrape the
Services, (d) interfere with security or availability, (e) use the Services
for spam or unsolicited commercial communications, or (f) violate any
applicable law.

## 7. User-Generated Content
You retain ownership of content you post (community posts, reviews,
messages, gallery submissions, uploaded files). You grant Birthright a
worldwide, non-exclusive, royalty-free, sublicensable license to host,
display, reproduce, adapt (for format only), and distribute your content
solely to operate and promote the Services. You represent that you have all
rights necessary to grant this license.

## 8. Community Standards
All community interaction is subject to the Content Moderation & Community
Standards Policy. Violations may result in content removal, account
suspension, or termination.

## 9. AI-Assisted Features
Portions of the Services use generative AI (product imagery, image captions,
the Help Assistant). AI outputs may contain errors and are not professional
advice — medical, mental-health, legal, or otherwise. Do not rely on AI
outputs in place of licensed professional judgment.

## 10. Not Therapy
Birthright is an educational platform. Nothing on the Services constitutes
psychotherapy, counseling, or medical treatment, and no clinician-patient
relationship is created. If you are in crisis, contact emergency services
or a qualified clinician.

## 11. Intellectual Property
Except for user-generated content licensed under §7, all content on the
Services — including the birthright wordmark, flame logo, taglines,
workshop materials, and Research articles — is owned by Birthright or its
licensors and protected by copyright, trademark, and other laws.

## 12. Third-Party Services
The Services rely on third-party sub-processors (see our Privacy Policy).
Your use of the Services is also subject to those providers' terms.

## 13. Disclaimers
THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF
ANY KIND. BIRTHRIGHT DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

## 14. Limitation of Liability
TO THE MAXIMUM EXTENT PERMITTED BY LAW, BIRTHRIGHT'S TOTAL LIABILITY FOR ANY
CLAIM ARISING OUT OF OR RELATING TO THE SERVICES IS LIMITED TO THE GREATER
OF (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM AND
(B) ONE HUNDRED U.S. DOLLARS. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL,
CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES.

## 15. Indemnification
You will indemnify and hold harmless Birthright, its officers, directors,
employees, volunteers, and partners from any claim or demand arising out of
your (a) violation of these Terms, (b) infringement of a third party's
rights, or (c) unlawful conduct. See also the Universal Indemnification &
Hold-Harmless Agreement at /legal/indemnification.

## 16. Dispute Resolution & Arbitration
> **Counsel: retain, revise, or remove based on jurisdiction.**
Any dispute arising out of or relating to these Terms or the Services will
be resolved by **binding individual arbitration** administered by the
American Arbitration Association under its Consumer Arbitration Rules. YOU
AND BIRTHRIGHT AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN
INDIVIDUAL CAPACITY AND NOT AS PART OF ANY CLASS OR REPRESENTATIVE ACTION.
Arbitration will take place in [STATE OF INCORPORATION]. Notwithstanding
the foregoing, either party may bring an individual small-claims action in
small-claims court.

## 17. Governing Law
These Terms are governed by the laws of the State of [STATE OF
INCORPORATION], without regard to conflict-of-laws principles.

## 18. Termination
We may suspend or terminate your account for any material breach of these
Terms. You may close your account at any time by contacting
hello@birthright.live.

## 19. Changes
We may update these Terms from time to time. Material changes will be
announced with reasonable notice via email or on-platform banner. Continued
use after the effective date constitutes acceptance.

## 20. Miscellaneous
- Severability: if any provision is unenforceable, the remainder remains in effect.
- No waiver: our failure to enforce a right is not a waiver.
- Entire agreement: these Terms together with the Privacy Policy and any
  linked policies form the entire agreement between you and Birthright.
- Contact: hello@birthright.live.
"""),

# ---------- 2. PRIVACY POLICY ----------
("02-privacy-policy", "Privacy Policy (Draft)", "Public-facing", """
# Privacy Policy — Birthright Foundation (Draft)

## 1. Scope
This Privacy Policy describes how Birthright Foundation ("Birthright,"
"we") collects, uses, discloses, and safeguards personal information in
connection with birthright.live and related services.

## 2. Personal Information We Collect
- **You provide us**: name, email, phone, shipping/billing address, account
  credentials (bcrypt-hashed), community and dispute content, uploaded
  files for vendor custom orders, workshop registrations, questions asked
  to our AI Help Assistant.
- **Automatically**: IP address, device and browser metadata, referrer,
  pages visited (see Cookie Notice).
- **From third parties**: payment metadata from Stripe (session IDs, last-4,
  charge status — never card numbers or CVV); routing metadata from
  Cloudflare.
- **Partner-facing accounts** additionally provide payout method
  identifiers (stored encrypted; only method type and last-4 in plaintext).

## 3. How We Use It
- To operate the Services (accounts, checkout, workshop registration,
  community, AI features)
- To communicate with you (receipts, workshop reminders, dispute updates,
  newsletter with your consent)
- To fulfill orders (share address with Printful, Lulu, or vendor partner)
- To pay Partners and reconcile wholesale amounts
- To improve the Services (analytics, image-caption search)
- To meet legal obligations (tax reporting, subpoena response)
- With your consent, for any other purpose disclosed at the point of
  collection

## 4. Legal Bases (EU/UK users)
Where GDPR/UK-GDPR applies we rely on (a) contract necessity (accounts,
purchases, workshops), (b) legitimate interests (security, product
improvement), (c) consent (marketing email, non-essential cookies), and
(d) legal obligation (tax and accounting).

## 5. Sub-Processors
We share personal information only with the following sub-processors, and
only for the purposes described:

| Sub-processor | Purpose | Data shared |
|---|---|---|
| Stripe | Payment processing, subscription billing, refunds | Name, email, address, order metadata |
| Resend | Transactional email | Name, email, order details, uploaded attachments (for vendor orders) |
| Printful | POD apparel/prints fulfillment | Name, shipping address, product variant |
| Lulu | POD book fulfillment | Name, shipping address, product |
| Google (Gemini) | AI image generation and captioning via Emergent LLM Key | Product descriptions/images |
| Anthropic (Claude) | Help Assistant via Emergent LLM Key | Question text + platform DB context |
| Cloudflare | DNS, email routing, DDoS mitigation | Domain/traffic metadata |
| Formester (via 7C's Farmstead) | Vendor reorder submissions | Name, email, phone, shipping address |
| Emergent | Application hosting | All Service data |
| GitHub | Source-code hosting | Source code (no customer data) |

Sub-processors are contractually bound to protect personal information and
process it only on our instructions where required.

## 6. Cookies
See our separate Cookie Notice.

## 7. Retention
- Account records: until you delete your account, plus 7 years for tax
  and accounting where required.
- Order records and receipts: 7 years.
- Community/DM content: retained while your account is active. On
  deletion, we anonymize or remove within 30 days except where retention
  is required by law or to resolve open disputes.
- AI Help Assistant conversation memory: session-scoped in server memory;
  logs of prompt/response text are retained 90 days for abuse review.
- Backup snapshots: rolling 30 days.

## 8. Your Rights
Depending on where you live you may have the right to:
- Access, correct, or delete your personal information
- Object to or restrict processing
- Portability (receive a copy in machine-readable format)
- Withdraw consent
- Not be subject to solely-automated decision-making with legal effect
  (we do not currently make such decisions)
- Opt out of "sale" or "sharing" (we do not sell personal information)

Submit requests to **privacy@birthright.live**. We respond within the
statutory timeframe (typically 30–45 days).

## 9. Data Transfers
We are based in the United States. If you access the Services from outside
the U.S., you consent to processing here. Where required, we rely on
Standard Contractual Clauses (SCCs) or equivalent transfer mechanisms.

## 10. Security
We maintain administrative, technical, and physical safeguards including
TLS-in-transit, bcrypt password hashing, encryption of sensitive payout
fields with an internal key, least-privilege admin access, and audit
logging. No system is perfectly secure; you use the Services at your risk.

## 11. Children
The Services are not directed to children under 18 and we do not knowingly
collect information from them. Contact privacy@birthright.live to request
deletion of a child's account.

## 12. Health-Adjacent Content
Community posts, dispute submissions, and workshops may discuss relational
trauma, attachment history, or mental-health topics. This content is not
protected health information (PHI) under HIPAA because we are not a covered
entity, but we treat it with heightened care and retain it per §7.

## 13. Changes
We will announce material changes with reasonable notice on-platform. The
"last updated" date at the top reflects the most recent revision.

## 14. Contact
Data Protection contact: **privacy@birthright.live**
Mailing address: [ENTITY LEGAL ADDRESS TO BE ADDED BY COUNSEL]
"""),

# ---------- 3. COOKIE NOTICE ----------
("03-cookie-notice", "Cookie & Tracking Notice (Draft)", "Public-facing", """
# Cookie & Tracking Notice — Birthright Foundation (Draft)

We use a small number of cookies and similar technologies to make the
Services work and to understand how they are used.

## 1. Categories of cookies we use
- **Strictly necessary**: session (authentication), CSRF/security,
  load-balancing. Cannot be disabled.
- **Functional**: cart contents, preferred language/theme, dismissed
  banners. Set only when you interact with the corresponding feature.
- **Analytics**: aggregated page-view and error telemetry. Non-identifying
  where possible.
- **Marketing / third-party ad cookies**: **NONE** at this time.

## 2. Third-party cookies
- **Stripe**: sets cookies at checkout to detect fraud and remember
  card sessions.
- **Cloudflare**: sets `__cf_bm` and similar cookies for bot management
  and to route requests. These are strictly necessary for security.

## 3. Do Not Track
We do not currently respond to Do Not Track browser signals. Where required
(e.g., California's Global Privacy Control), we honor "sale/share" opt-out
signals — noting that we do not sell or share personal information for
cross-context behavioral advertising.

## 4. How to control cookies
- Most browsers let you refuse cookies or delete them.
- Disabling strictly-necessary cookies will break sign-in and checkout.
- Contact privacy@birthright.live if you have questions.

## 5. Changes
If we add tracking cookies (e.g., an analytics vendor with identifiers), we
will present a consent banner and update this notice.
"""),

# ---------- 4. INDEMNIFICATION ----------
("04-indemnification-hold-harmless",
 "Universal Indemnification & Hold-Harmless Agreement (Draft)",
 "Public-facing",
 """
# Universal Indemnification & Hold-Harmless Agreement (Draft)

This agreement supplements the Terms of Service. By using birthright.live,
attending a workshop, participating in the community, or accepting a
partner or facilitator role you enter into this agreement.

## 1. Nature of the Services
Birthright is an educational and community platform. Content on the
Services — including workshops, articles, community posts, and the AI Help
Assistant — is **educational only** and is not medical, psychological, or
legal advice. No clinician-patient, attorney-client, or fiduciary
relationship is created.

## 2. Personal Responsibility
You are solely responsible for how you apply anything you read, watch,
hear, or receive from the Services. Emotional or relational subject matter
may surface intense reactions; you agree to seek qualified professional
help if needed.

## 3. Release
To the fullest extent permitted by law, you release Birthright Foundation,
its officers, directors, employees, volunteers, facilitators, artists,
vendors, and partners (collectively "Released Parties") from any and all
claims, demands, damages, or causes of action arising out of your use of
the Services or your reliance on any content, product, workshop, or AI
output made available through them.

## 4. Indemnification
You will defend, indemnify, and hold harmless the Released Parties from
any third-party claim arising out of (a) your breach of these Terms or any
policy referenced by them, (b) your infringement of another person's
rights (including IP or privacy), (c) your unlawful conduct on the
platform, or (d) content you upload or transmit through the Services.

## 5. Physical Products
Physical goods sold or referred through the Services carry their own
manufacturer/vendor warranties. Birthright's liability for defective
product is limited to refund or replacement per our Refund & Returns
Policy.

## 6. Facilitators & Volunteers
Facilitators and volunteers who host or contribute to Birthright programs
are covered by this agreement as Released Parties when acting in that
capacity, and are separately covered by their role-specific agreements.

## 7. Not a Substitute for Care
If you are experiencing a mental-health crisis, thoughts of self-harm, or
an emergency, contact emergency services (911 in the U.S.) or your local
crisis line. Birthright is not a crisis or clinical service.

## 8. Governing Law & Dispute Resolution
This agreement is governed by the laws of [STATE OF INCORPORATION] and any
dispute is resolved through the mechanism in the Terms of Service.

## 9. Effective Date
This agreement is effective when you register, purchase, or otherwise
interact with the Services on or after its published effective date.
"""),

# ---------- 5. FACILITATOR SERVICES AGREEMENT ----------
("05-facilitator-services-agreement",
 "Facilitator Services Agreement + IP Assignment (Draft)",
 "Partner agreements",
 """
# Facilitator Services Agreement + IP Assignment (Draft)

This Agreement is entered into on the Effective Date between Birthright
Foundation ("Birthright") and the individual named below ("Facilitator").

## 1. Services
Facilitator will design and lead workshops and related educational
sessions ("Sessions") through the Birthright platform. Sessions may be
live-facilitated, self-paced, or recorded.

## 2. Compensation
- Per-session fee: [$ AMOUNT] paid within 15 days of session close.
- Revenue-share on paid registrations: [X%] of net registration revenue
  after payment-processor fees and applicable sliding-scale discounts.
- Optional flat monthly retainer available for lead facilitators.

## 3. Independent Contractor
Facilitator is an independent contractor, not an employee. Facilitator is
responsible for their own taxes and will complete Form W-9 (or W-8 for
non-U.S. persons). Birthright will issue Form 1099-NEC where required.

## 4. Intellectual Property
- Facilitator retains ownership of pre-existing materials brought to
  Sessions and grants Birthright a perpetual, non-exclusive, royalty-free
  license to use them in connection with the Session and its recording.
- All Session recordings, transcripts, workbooks, and derivative
  educational materials created for or during a Birthright Session are
  **works made for hire** and, to the extent not works for hire, are
  hereby assigned to Birthright.
- Facilitator's name, bio, and likeness may be used to promote the
  Session on the Services during the term and for one (1) year afterward.

## 5. Standards of Practice
Facilitator will (a) hold appropriate credentials if representing a
regulated modality, (b) comply with the Content Moderation & Community
Standards Policy, (c) never provide clinical advice unless separately
licensed and clearly acting outside the Birthright program, and (d) refer
participants to emergency services if a safety concern arises.

## 6. Confidentiality
Facilitator will not disclose participant personal information outside the
Session and will comply with the Privacy Policy.

## 7. Term & Termination
Either party may terminate this Agreement upon 30 days' written notice.
Birthright may terminate immediately for cause (material breach,
misconduct, or safety risk).

## 8. Indemnification
Facilitator will indemnify Birthright for any claim arising out of
Facilitator's own acts, omissions, or breach of this Agreement. Birthright
will indemnify Facilitator for any claim arising out of Birthright's own
gross negligence or willful misconduct.

## 9. Insurance
Facilitator is encouraged to maintain professional liability insurance
appropriate to their modality. Birthright maintains general liability
insurance covering platform operations.

## 10. Miscellaneous
Governing law, entire-agreement, severability, and no-waiver clauses
consistent with the Terms of Service.

**Facilitator name**: __________________________
**Signature**: __________________________  **Date**: __________
**Birthright signatory**: __________________________
"""),

]  # end of first batch — continued below

# Second half of the catalog to keep this file under 300 lines each
DOCS += [

# ---------- 6. ARTIST CONSIGNMENT ----------
("06-artist-consignment-agreement",
 "Artist Consignment / Gallery Partner Agreement (Draft)",
 "Partner agreements",
 """
# Artist Consignment / Gallery Partner Agreement (Draft)

This Agreement is between Birthright Foundation and the artist named below
("Artist"). It governs the sale of Artist's work through the Birthright
gallery at /gallery.

## 1. Consignment
Artist consigns to Birthright the works listed in Artist's dashboard for
online display and sale. Artist retains title to each work until sold.

## 2. Pricing
Artist sets the list price for each work. Birthright collects payment from
the buyer at list price plus a **20% Foundation hospitality markup** which
Birthright retains. Artist receives the list price minus payment-processor
fees, remitted per §5.

## 3. Fulfillment
Artist ships each sold work directly to the buyer within 5 business days
of receiving the shipping notification and packing slip from Birthright.

## 4. Authenticity Warranty
Artist represents that each consigned work is original, created by Artist,
does not infringe any third-party intellectual property, and is not
subject to any lien or restriction.

## 5. Payment
Payouts to Artist are made monthly within 15 days of month-end via
Stripe Connect (once activated) or via manual bank transfer / check.
Birthright will issue Form 1099-NEC when reporting thresholds are met.

## 6. Digital Rights
Artist grants Birthright a limited license to reproduce photographs of
consigned works on the Services for marketing and cataloging purposes,
including on social media referencing the Services, for the duration of
consignment plus one (1) year.

## 7. Featured Slot Purchase
Artist may separately pay to be featured in the homepage carousel
(/dashboard/partner/featured). Featured-slot fees are non-refundable and
do not carry any implied warranty of sales performance.

## 8. Returns
If a buyer returns a work under the Refund & Returns Policy, Artist will
receive the work back and forfeit that sale. The buyer's refund covers the
full list price plus markup; Artist forfeits their portion only.

## 9. Term & Removal
Either party may remove any work at any time by written notice. Existing
orders in flight are honored.

## 10. IP Indemnity
Artist will indemnify Birthright for any third-party claim of copyright,
trademark, or moral-rights infringement in a consigned work.

## 11. Miscellaneous
Independent contractor status; governing law per Terms of Service;
severability; entire-agreement.

**Artist**: __________________________  **Signature**: __________________
**Effective date**: __________  **Birthright signatory**: ______________
"""),

# ---------- 7. VENDOR SUPPLIER ----------
("07-vendor-supplier-agreement",
 "Vendor Supplier / Dropship Agreement (Draft, 7C's Farmstead first)",
 "Partner agreements",
 """
# Vendor Supplier / Dropship Agreement (Draft)

Between Birthright Foundation and **7C's Farmstead** ("Vendor"). This
Agreement governs Vendor's fulfillment of orders placed on birthright.live.

## 1. Scope
Vendor supplies the SKUs listed in Exhibit A (initially the Founder
Collection leather-engraved patches). Birthright markets, sells, and
collects payment; Vendor manufactures and ships directly to the buyer.

## 2. Pricing & Payment
- Retail (buyer pays Birthright): as listed on birthright.live.
- Wholesale (Birthright pays Vendor): $[5.00] per patch, or as revised in
  Exhibit A.
- Shipping cost (buyer pays Birthright; Birthright reimburses Vendor):
  actual cost or agreed flat rate per Exhibit A.
- Birthright remits wholesale + shipping within 15 days of order or per
  the schedule in Exhibit A.

## 3. Order Flow
1. Buyer completes checkout on birthright.live.
2. Birthright emails Vendor a prefilled order via Vendor's own custom
   order form (Formester) with all buyer, product, and shipping details.
3. Vendor fulfills using existing SKU files already on record — **no
   customization is permitted** unless separately agreed.
4. Vendor ships within [X] business days and provides tracking to
   orders@birthright.live.

## 4. Quality & Compliance
Vendor represents that all products conform to their listed description,
are free of material defects, and comply with applicable consumer safety
laws.

## 5. IP Ownership
Birthright owns the SKU designs and engraving text ("Birthright Marks"
described in Exhibit B). Vendor may use them only to fulfill Birthright
orders and may not sell the same designs to other customers without
written consent.

## 6. IP Indemnity
Each party indemnifies the other for third-party IP claims arising from
that party's contributions (Birthright: designs/text; Vendor: manufacturing
processes, materials).

## 7. Returns & Defects
If a buyer initiates a return under the Refund & Returns Policy for a
defect attributable to Vendor, Vendor will accept the return and refund
Birthright the wholesale + shipping amount within 15 days.

## 8. Data Handling
Buyer personal information is provided only to fulfill the specific order.
Vendor will not use, retain beyond fulfillment necessity, or sell buyer
information. Standard sub-processor DPA language attached as Exhibit C.

## 9. Term & Termination
Initial term of 12 months, renewing month-to-month thereafter. Either
party may terminate for convenience on 30 days' notice or immediately for
material breach.

## 10. Miscellaneous
Governing law per Terms of Service; independent contractors; entire
agreement.

**7C's Farmstead**: __________________________
**Signature**: __________________________  **Date**: __________
**Birthright signatory**: __________________________
"""),

# ---------- 8. COMMUNITY PARTNER REFERRAL ----------
("08-community-partner-referral-agreement",
 "Community Partner Referral Agreement (Draft)",
 "Partner agreements",
 """
# Community Partner Referral Agreement (Draft)

Between Birthright Foundation and the referrer named below ("Partner").

## 1. Referral Program
Partner will promote Birthright and drive traffic to birthright.live using
their assigned referral link (`/r/{slug}`). A 30-day cookie window
attributes purchases made after the referred visit.

## 2. Compensation
- Partner earns [X%] of net revenue on attributed product sales, workshop
  registrations, and sponsorship signups, where "net" is gross less
  payment-processor fees and any refunds.
- Compensation accrues at order fulfillment and becomes payable at the
  next monthly close.
- Minimum payout: $50. Balances below the minimum roll forward.

## 3. Payment Method
Payouts are made via ACH (once Stripe Connect is activated) or manual
transfer as agreed. Partner will complete Form W-9 (or W-8 for non-U.S.
persons). Birthright will issue Form 1099-NEC where required.

## 4. Clawback
If a referred purchase is refunded, the corresponding referral commission
is clawed back from Partner's next payout (see `refund_cascades` in the
platform).

## 5. Conduct
Partner will not (a) run paid ads bidding on the "birthright" trademark,
(b) misrepresent Birthright's services, (c) engage in spam, unsolicited
email, or cookie-stuffing, (d) offer unauthorized coupons or rebates.

## 6. IP Use
Partner may use approved Birthright logos and copy provided under
`/dashboard/partner/assets`. Trademark use is limited to identifying
Birthright and the referral relationship.

## 7. Term & Termination
Either party may terminate on 15 days' notice. Termination does not
extinguish already-accrued commissions.

## 8. Independent Contractor
Partner is an independent contractor with no authority to bind
Birthright.

## 9. Confidentiality
Partner will treat non-public referral data (attribution reports, payout
detail) as confidential.

## 10. Miscellaneous
Governing law per Terms of Service; entire agreement.

**Partner**: __________________________  **Effective date**: __________
"""),

# ---------- 9. SPONSORSHIP ----------
("09-sponsorship-agreement",
 "Sponsorship Agreement / Sponsor Recognition Consent (Draft)",
 "Partner agreements",
 """
# Sponsorship Agreement / Sponsor Recognition Consent (Draft)

## 1. Sponsorship Tiers
Sponsor commits to a recurring monthly or annual contribution at one of
the tiers listed at /sponsor. Contributions may or may not be tax-
deductible depending on Birthright's federal tax status at the time of
the gift; consult your tax advisor.

## 2. Recognition
Sponsor consents to the recognition listed at their tier, which may
include: name/logo on the "Our Sponsors" page, listing in the monthly
newsletter, and public acknowledgment at select workshops. Sponsor may
opt out of public recognition at any time by writing
hello@birthright.live.

## 3. Perks
Tier-specific perks (e.g., workshop credits, early access) are described
in Exhibit A. Perks are non-transferable and have no cash value.

## 4. Quid Pro Quo
Where a Sponsor receives tangible perks in exchange for their gift,
Birthright will disclose the fair market value of the perks in accordance
with IRS Publication 1771 (once 501(c)(3) status is granted). Only the
excess of the gift over the perk value is potentially deductible.

## 5. Trademark Use
Birthright will use Sponsor's name and mark only in a manner consistent
with Sponsor's brand guidelines (linked in the sponsor onboarding form).

## 6. Cancellation
Sponsor may cancel a recurring gift at any time via the dashboard.
Cancellation is prospective; already-paid periods are not refunded.

## 7. No Endorsement
Sponsorship does not constitute Birthright's endorsement of Sponsor's
products or services, and vice versa.

## 8. Miscellaneous
Governing law per Terms of Service; entire agreement.
"""),

# ---------- 10. SLIDING SCALE / SCHOLARSHIP ----------
("10-sliding-scale-scholarship-terms",
 "Sliding-Scale & Scholarship Terms (Draft)",
 "Public-facing",
 """
# Sliding-Scale & Scholarship Terms (Draft)

Birthright offers sliding-scale pricing on many workshops so that cost
does not exclude anyone from the community.

## 1. Tiers
Each participating workshop lists three price points:
- **Supported** — below cost. For participants with financial constraint.
- **Sustaining** — actual cost of running the session.
- **Solidarity** — above cost. Helps subsidize Supported seats.

## 2. Trust-Based
Selection is trust-based. We do not verify income. We ask that you choose
in good faith and adjust up or down over time as your circumstances
change.

## 3. Scholarship Seats
A limited number of no-cost scholarship seats are held for each open
workshop. Apply via the "Request scholarship" link on the workshop page.
Approval is at facilitator discretion.

## 4. Refunds
Same as our general Refund & Returns Policy: refunds available up to 48
hours before the session start time.

## 5. No Downgrade Guilt
Choosing a lower tier does not affect the experience you receive.
Facilitators do not know which tier any participant selected.
"""),

# ---------- 11. BOARD OFFICER ----------
("11-board-officer-agreement",
 "Board Member / Officer Agreement + D&O Coverage (Draft)",
 "Governance",
 """
# Board Member / Officer Agreement + D&O Coverage (Draft)

Between Birthright Foundation and the individual named below ("Director").

## 1. Role
Director accepts election/appointment to the Board of Directors of
Birthright Foundation and agrees to serve in accordance with the Bylaws.

## 2. Duties
Director will fulfill the duties of care, loyalty, and obedience, attend
scheduled meetings, and act in the best interests of Birthright and its
mission.

## 3. Term
Director's term is [2 years] per the Bylaws, renewable per Board election.

## 4. Compensation
Board service is generally uncompensated. Reimbursement of reasonable
out-of-pocket expenses is provided upon receipted request.

## 5. Conflicts of Interest
Director will disclose any actual or potential conflict of interest per
the Conflict-of-Interest Policy and recuse from votes as appropriate.

## 6. Confidentiality
Director will treat non-public Board deliberations and organizational
information as confidential, both during and after service.

## 7. Indemnification
Birthright will indemnify Director to the fullest extent permitted by
[STATE] law and the Bylaws for actions taken in good faith in the
Director's official capacity.

## 8. D&O Insurance
Birthright will maintain Directors & Officers liability insurance at a
level appropriate to its operations. A summary of coverage is available
to Director upon request.

## 9. Removal & Resignation
Director may resign at any time by written notice to the Board Chair.
Director may be removed per the Bylaws.

## 10. Miscellaneous
Governing law per Bylaws; entire agreement.

**Director**: __________________________  **Effective**: __________
**Board Chair**: __________________________
"""),

# ---------- 12. VOLUNTEER ----------
("12-volunteer-agreement",
 "Foundation Working-Group Volunteer Agreement (Draft)",
 "Governance",
 """
# Foundation Working-Group Volunteer Agreement (Draft)

Between Birthright Foundation and the volunteer named below ("Volunteer").

## 1. Role
Volunteer will contribute time to a Birthright working group as described
in Exhibit A.

## 2. Independent Volunteer
Volunteer serves as an unpaid independent volunteer, not as an employee
or independent contractor. No wages, benefits, or workers-compensation
coverage attaches.

## 3. Time Commitment
Volunteer expects to contribute approximately [X hours per month] and may
adjust with reasonable notice.

## 4. Confidentiality
Volunteer will treat non-public Birthright information as confidential.

## 5. IP Assignment
Any deliverables created by Volunteer in the course of the working group
are works made for hire (or, to the extent not, are hereby assigned to
Birthright).

## 6. Release
Volunteer acknowledges that working-group activity is voluntary and
releases Birthright from any claim arising from Volunteer's own conduct.

## 7. Conduct
Volunteer will comply with the Community Standards, the Conflict-of-
Interest Policy, and applicable law.

## 8. Termination
Either party may end the arrangement at any time on reasonable notice.

**Volunteer**: __________________________  **Effective**: __________
"""),

# ---------- 13. OMBUDSMAN CHARTER ----------
("13-ombudsman-charter",
 "Ombudsman Charter (Draft)",
 "Governance",
 """
# Ombudsman Charter (Draft)

## 1. Purpose
The Ombudsman is an independent role responsible for receiving,
investigating, and mediating disputes within the Birthright community.

## 2. Appointment
The Board appoints the Ombudsman for a term of [2 years], renewable.
The Ombudsman may be removed only by a supermajority Board vote.

## 3. Independence
The Ombudsman does not report to any operating officer and communicates
findings directly to the Board.

## 4. Scope
Disputes cognizable by the Ombudsman include: participant-vs-facilitator
concerns, buyer-vs-vendor complaints beyond the Refund & Returns Policy,
allegations of Community Standards violations, and grievances against
Birthright officers or volunteers.

Not in scope: emergencies (which are referred to local emergency
services), clinical or legal complaints (which are referred out), and
matters already in litigation or arbitration.

## 5. Process
1. Intake through `/dashboard/disputes` or by email to ombudsman@birthright.live.
2. Acknowledgement within 3 business days.
3. Preliminary review within 15 business days.
4. Mediation or formal recommendation within 45 business days.
5. Right of appeal to the full Board within 30 days of recommendation.

## 6. Confidentiality
The Ombudsman will keep all identifying information confidential to the
extent possible while conducting the review.

## 7. Anti-Retaliation
No party will be retaliated against for raising a good-faith concern
through the Ombudsman.

## 8. Records
The Ombudsman maintains a summary record of each matter, retained for
7 years.

## 9. Reporting
The Ombudsman provides an anonymized quarterly report to the Board.
"""),

# ---------- 14. COMMUNITY STANDARDS ----------
("14-community-standards",
 "Content Moderation & Community Standards Policy (Draft)",
 "Public-facing",
 """
# Content Moderation & Community Standards Policy (Draft)

## 1. Our Ask
Birthright is a community focused on secure connection. Please participate
with courage, honesty, and care. This policy explains what is not
acceptable and how we enforce it.

## 2. Not Allowed
- Harassment, targeted abuse, hate speech
- Threats of violence or incitement
- Doxxing or sharing another person's private information
- Sexual content involving minors (mandatory report to authorities)
- Illegal content or activity
- Spam, promotions, or unsolicited commercial messages
- Impersonation of Birthright staff or another member
- Circumventing moderation (e.g., ban evasion)

## 3. Sensitive Topics
Discussions of trauma, mental health, and relational harm are welcome and
often central to the community. Please add content warnings for intense
material. If you are describing self-harm intent, our team is required to
respond and connect you to appropriate resources.

## 4. Enforcement
- Warning
- Content removal
- Temporary suspension
- Permanent ban
- Referral to law enforcement in cases of imminent harm or illegal
  content

## 5. Reporting
Report content via the report link on any post, or by emailing
ombudsman@birthright.live.

## 6. Appeals
Sanctioned users may appeal to the Ombudsman under the Ombudsman Charter.

## 7. Transparency
We publish an anonymized annual report of the number of actions taken by
category.
"""),

# ---------- 15. REFUND ----------
("15-refund-returns-policy",
 "Refund & Returns Policy (Draft, Public)",
 "Public-facing",
 """
# Refund & Returns Policy (Draft)

## 1. Products
- **Standard-fulfillment products** (Printful, Lulu): returnable within
  30 days of delivery in unused condition. Return shipping paid by buyer
  unless the item arrives defective.
- **Vendor-partner products** (e.g., 7C's Farmstead leather patches):
  returnable within 30 days for defect only. Custom or personalized
  items are non-returnable except in case of defect or shipment error.
- **Gallery artwork**: returnable within 14 days of delivery. Buyer pays
  return shipping and insurance.

## 2. Workshops
Full refund available up to 48 hours before the session start time. No
refund within 48 hours except in cases of documented emergency. Recorded
sessions are non-refundable once accessed.

## 3. Subscriptions & Sponsorships
Cancellation is prospective. Already-paid periods are not refunded except
where required by law.

## 4. AI Wallet
Prepaid AI credits are non-refundable and non-transferable.

## 5. Donations
Donations are generally non-refundable. We will consider requests within
30 days of the gift in exceptional circumstances.

## 6. How to Request
Email hello@birthright.live with your order ID and reason. We respond
within 3 business days.

## 7. Refund Cascades
When a refund is issued on a Partner-attributed sale, the corresponding
partner commission is clawed back per the Partner agreements.
"""),

# ---------- 16. SALES TAX ----------
("16-sales-tax-registration-plan",
 "Sales-Tax Registration Plan (Draft)",
 "Internal / Compliance",
 """
# Sales-Tax Registration Plan (Draft)

## 1. Objective
Bring Birthright into compliance with state sales-tax collection
obligations arising from remote sales of tangible personal property.

## 2. Nexus Analysis
Post-Wayfair (South Dakota v. Wayfair, 2018) states may impose economic
nexus once a remote seller exceeds a revenue or transaction threshold.
Common thresholds: $100,000 in sales OR 200 transactions in the prior
calendar year.

**Action items for counsel/accountant**:
1. Review the last 12 months of Stripe sales data (available at
   `/admin/reports`) grouped by ship-to state.
2. Identify states in which either the revenue or the transaction
   threshold has been met.
3. Register for a sales-tax permit in each such state.
4. Configure Stripe Tax (or equivalent) to collect and remit going
   forward.

## 3. Product Taxability
- Apparel, prints, mugs, bags, journals, patches: taxable in most states.
- Digital workshops: taxability varies (some states tax digital
  educational products, some exempt when accompanied by live instruction).
- Nonprofit exemption: **not automatic**. Even if 501(c)(3), most states
  require the buyer (not the seller) to hold the exemption to purchase
  tax-free.

## 4. Marketplace Facilitator Considerations
For any items fulfilled via Printful or Lulu, confirm whether they act as
"marketplace facilitator" for tax purposes. If yes, we may not need to
register in states where they already remit. Document this in a
compliance memo.

## 5. Filing Cadence
Monthly, quarterly, or annually depending on state and volume.
"""),

# ---------- 17. TRADEMARK ----------
("17-trademark-filings-plan",
 "Trademark Filings Plan (Draft)",
 "Internal / IP",
 """
# Trademark Filings Plan (Draft)

## 1. Marks to Protect
1. Wordmark: **BIRTHRIGHT** (standard characters)
2. Composite: **birthright** wordmark + ember-gold flame logo
3. Slogan (optional): **"You are the founder of your own love story"**
4. Slogan (optional): **"Secure connection is your birthright"**

## 2. Classes (International Classes of Goods/Services)
- Class 9 — downloadable educational materials, software
- Class 16 — printed matter (journals, books)
- Class 25 — clothing (apparel merchandise)
- Class 35 — online retail store services
- Class 41 — educational services (workshops)
- Class 45 — online social-networking services

## 3. Search
Before filing, run a comprehensive knock-out search on USPTO TESS plus
common-law usage. Consider international searches (WIPO Madrid) if
international expansion is anticipated.

## 4. Filing Strategy
- File 1(a) if in use in commerce (most likely for BIRTHRIGHT and the
  composite logo — both are on the live site).
- File 1(b) intent-to-use for slogans if not yet in commercial use as
  slogans (as opposed to prose in copy).

## 5. Domain & Social
- birthright.live secured.
- Consider defensive registrations of adjacent TLDs (.org, .foundation)
  and social handles.

## 6. Enforcement
Register domain-alert and USPTO watches. Draft a takedown SOP for
infringing use on Etsy, Amazon, Instagram, etc.
"""),

# ---------- 18. COPYRIGHT ----------
("18-copyright-registration-strategy",
 "Copyright Registration Strategy (Draft)",
 "Internal / IP",
 """
# Copyright Registration Strategy (Draft)

## 1. Assets Worth Registering
- **Workshop curricula** — script, workbook, slide deck. Register as a
  literary work.
- **Research articles** — long-form articles under /research. Register in
  batches per calendar quarter as a compilation.
- **Video recordings** of workshops — register as an audiovisual work.
- **Original photography** — group-register per calendar year.
- **AI-generated storefront imagery** — **do not register**. Under current
  U.S. Copyright Office guidance, AI-generated works generally are not
  copyrightable absent significant human authorship. Document the human
  authorship (prompting, curation, layout) if we decide to attempt
  registration on any composite piece.

## 2. Cadence
Quarterly batch filings for articles and photos; per-work filing for
workshop curricula upon completion.

## 3. Notice
Add © Birthright Foundation [year] at the footer of each protected work.

## 4. Assignments
Ensure each contributor (facilitators, contract writers, videographers,
photographers) signs a written IP assignment or work-for-hire clause.
"""),

# ---------- 19. DPA TEMPLATE ----------
("19-data-processing-agreement-template",
 "Data Processing Agreement Template (Draft)",
 "Governance",
 """
# Data Processing Agreement (Template) (Draft)

This template is executed with each sub-processor that handles personal
information on Birthright's behalf.

## 1. Parties
Between Birthright Foundation ("Controller") and [SUB-PROCESSOR]
("Processor").

## 2. Scope of Processing
Processor will process personal information only for the purpose of
providing the service described in the underlying service agreement.

## 3. Categories of Data
Refer to Exhibit A. Typically: buyer/member name, email, phone, address,
order metadata; may include uploaded files.

## 4. Data Subject Rights
Processor will assist Controller in responding to data-subject requests
under GDPR, CCPA, and analogous laws within reasonable timeframes.

## 5. Security
Processor will maintain reasonable and appropriate technical and
organizational safeguards, including encryption in transit, access
controls, and audit logging.

## 6. Sub-Processors
Processor will not engage further sub-processors without prior notice to
Controller and provides a mechanism for Controller to object.

## 7. Cross-Border Transfers
Where personal information is transferred out of the EEA, UK, or
Switzerland, the parties incorporate the Standard Contractual Clauses
(2021) as Exhibit B.

## 8. Breach Notification
Processor will notify Controller of any confirmed personal-data breach
within 72 hours.

## 9. Deletion & Return
On termination, Processor will delete or return all personal information
within 30 days, except where retention is required by law.

## 10. Audit
Controller may audit Processor's compliance no more than once per year
on reasonable prior notice, or as required by law.

## 11. Governing Law
Same as underlying service agreement.
"""),

# ---------- 20. NONPROFIT GOVERNANCE BUNDLE ----------
("20-nonprofit-governance-bundle",
 "Nonprofit Governance Bundle (Draft — Articles, Bylaws, COI, Whistleblower, Retention)",
 "Governance",
 """
# Nonprofit Governance Bundle (Draft)

Five documents required for or supporting a Form 1023 filing.

---

## 20.1 Articles of Incorporation (Draft skeleton)

**Article I — Name**: Birthright Foundation.

**Article II — Purpose**: The Corporation is organized exclusively for
charitable and educational purposes within the meaning of Section
501(c)(3) of the Internal Revenue Code. Its specific purpose is to
educate, equip, and support individuals and communities in developing
secure attachment and healthy relational bonds through workshops,
publications, community programs, and related activities.

**Article III — Nonprofit Status**: The Corporation is a nonprofit
corporation. No part of the net earnings shall inure to the benefit of
any private individual.

**Article IV — Political & Legislative Activities**: No substantial part
of the Corporation's activities shall be carrying on propaganda or
attempting to influence legislation. The Corporation shall not
participate in any political campaign.

**Article V — Dissolution**: Upon dissolution, assets shall be
distributed for one or more exempt purposes under Section 501(c)(3) or
to the federal, state, or local government for a public purpose.

**Article VI — Registered Agent**: [TO BE COMPLETED BY COUNSEL].

**Article VII — Initial Directors**: [NAMES / ADDRESSES BY COUNSEL].

---

## 20.2 Bylaws (Draft skeleton)

**Article I — Offices**. Principal office: [TBD].

**Article II — Members**. The Corporation shall have no members. All
governance authority is vested in the Board of Directors.

**Article III — Board of Directors**.
- Number: no fewer than 3, no more than 11.
- Term: 2 years, staggered.
- Election: by majority of the sitting Board.
- Meetings: at least quarterly; annual meeting in January.
- Quorum: majority of directors then in office.
- Voting: majority of those present, unless a supermajority is required
  elsewhere in these Bylaws.

**Article IV — Officers**. Chair, Vice Chair, Secretary, Treasurer.
Terms of 1 year, elected annually by the Board.

**Article V — Committees**. Standing committees: Finance, Governance,
Ombudsman. Ad hoc committees as the Board deems necessary.

**Article VI — Indemnification**. See separate Indemnification Policy.

**Article VII — Amendments**. Bylaws may be amended by two-thirds vote
of the Board.

---

## 20.3 Conflict-of-Interest Policy (Draft)

**1. Purpose**. Protect the Corporation's interest when it enters into a
transaction or arrangement that might benefit the private interest of a
director, officer, or key employee.

**2. Definition of Interest**. A Financial Interest exists when a person
has, directly or indirectly through business, investment, or family, an
ownership or investment interest in an entity with which the Corporation
transacts, or a compensation arrangement.

**3. Duty to Disclose**. Interested persons must disclose the existence
and nature of the Financial Interest.

**4. Recusal**. Interested persons will not vote on the matter and may
be asked to leave the meeting for the deliberation.

**5. Records**. Board minutes will record the disclosure, the alternative
transactions considered, and the vote.

**6. Annual Statements**. Each director signs an annual conflict-of-
interest disclosure statement.

---

## 20.4 Whistleblower Policy (Draft)

**1. Purpose**. Encourage good-faith reports of illegal or unethical
conduct without fear of retaliation.

**2. Reporting Channels**. Reports may be submitted to the Ombudsman
(ombudsman@birthright.live), any Board member, or the Chair.

**3. Anti-Retaliation**. No employee, contractor, volunteer, or partner
will be terminated, demoted, harassed, or otherwise disadvantaged for
making a good-faith report.

**4. Confidentiality**. Reports are kept confidential to the extent
possible.

**5. Investigation**. Reports are investigated promptly by the
Ombudsman or a designee.

**6. False Allegations**. Knowingly false reports are subject to
disciplinary action.

---

## 20.5 Document Retention Policy (Draft)

| Record type | Retention |
|---|---|
| Articles, Bylaws, minutes | Permanent |
| Tax returns and supporting records | 7 years |
| Financial statements and audits | Permanent |
| Bank statements and reconciliations | 7 years |
| Contracts and agreements | Term + 7 years |
| Personnel and volunteer records | Term + 7 years |
| Donor records | 7 years (or longer if grant conditions require) |
| Community content (posts, DMs, disputes) | Per Privacy Policy §7 |
| Payment records (Stripe) | 7 years |
| Insurance policies | Permanent |
| Real property records | Permanent |

Records may be destroyed at the end of the retention period only after
confirmation there is no pending litigation, audit, or investigation.
"""),

# ---------- 21. CHARITABLE SOLICITATION ----------
("21-charitable-solicitation-plan",
 "State Charitable Solicitation Registration Plan (Draft)",
 "Internal / Compliance",
 """
# State Charitable Solicitation Registration Plan (Draft)

## 1. Background
Most U.S. states require nonprofits soliciting donations from residents
to register with a state agency (typically the Attorney General or
Secretary of State) before soliciting.

## 2. Solicitation Method
Birthright solicits online (birthright.live/support, /sponsor, /donate)
which reaches residents of every state that permits online use. Under
the "Unified Registration Statement" and interpretive guidance,
web-based solicitation generally triggers registration in states with
a solicitation statute.

## 3. Action Items
1. Wait until 501(c)(3) determination letter is received (registration
   applications typically require it).
2. Register in the following priority states first (states with the
   largest online donation history from our Stripe data):
   - California, New York, Florida, Texas, Massachusetts,
     Pennsylvania, Illinois — as a starting set.
3. Consider the Unified Registration Statement for states that accept
   it.
4. Track annual renewal deadlines per state.
5. Add a state-specific disclosure block to donation receipts and to
   the /support page.

## 4. Disclosure Blocks (samples)
- Florida: "A COPY OF THE OFFICIAL REGISTRATION AND FINANCIAL
  INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES
  BY CALLING TOLL-FREE 1-800-HELP-FLA…"
- New York: "A copy of the latest annual report may be obtained from
  the organization or from the Office of the Attorney General…"
- (Full block library to be compiled by counsel or a specialist vendor
  such as Harbor Compliance.)

## 5. Vendor Option
Consider engaging a compliance vendor (Harbor Compliance, Labyrinth, or
Foundation Group) to manage annual filings; cost typically $50–$150 per
state per year plus one-time onboarding.
"""),
]  # end DOCS


def write_all():
    written = []
    for slug, display_name, category, body in DOCS:
        path = OUT / f"{slug}.md"
        content = (
            DISCLAIMER_TOP
            + "\n\n"
            + body.strip()
            + "\n"
            + DISCLAIMER_BOTTOM
        )
        path.write_text(content)
        written.append((slug, display_name, category, path))
        print(f"  ✓ {path.name}  ({len(content) // 1024} KB)")

    # Emit a manifest we can import from routers/legal.py so the doc-shelf
    # doesn't need to be hand-edited every time a doc is added.
    manifest_lines = [
        "# AUTO-GENERATED by scripts/generate_legal_drafts.py — do not edit by hand.",
        "# Regenerate with: python scripts/generate_legal_drafts.py",
        f"# Last generated: {datetime.utcnow().isoformat()}Z",
        "",
        "DRAFT_LEGAL_DOCS = [",
    ]
    for slug, display_name, category, _ in written:
        manifest_lines.append(
            f'    {{"slug": "{slug}", "display_name": "{display_name}", '
            f'"category": "{category}"}},'
        )
    manifest_lines.append("]\n")
    (OUT / "_manifest.py").write_text("\n".join(manifest_lines))
    print(f"\nWrote {len(written)} drafts + manifest to {OUT}")


if __name__ == "__main__":
    write_all()
